### ISSUE TITLE
Push Acces 

### ISSUE THREAD

**Issue by MaartenBlomme** [inbo/geo-ict-student-project-2018#2]
Dag Stijn, is het mogelijk om ons push acces te geven zodat we code kunnen uploaden? 
@stijnvanhoey

**Comment by stijnvanhoey** [comment]
@MaartenBlomme die write (push) rechten hebben jullie, maar ik zag dat je je invite nog niet hebt geactiveerd.  In je mailbox zit normaal nog eens je invite.

**Comment by MaartenBlomme** [comment]
Bedankt! Ik had denk ik toen op de verkeerde link geklikt.
