### ISSUE TITLE
Betekenis kolommen

### ISSUE THREAD

**Issue by ThibeautFormesyn** [inbo/geo-ict-student-project-2018#3]
Bij het overlopen van de data waren er enkele kolommen die niet meteen duidelijk waren. 

- is_active: deze kolom lijkt leeg + we weten niet goed wat jullie er mee bedoelen
- pressure: waarschijnlijk bedoelen jullie de luchtdruk, maar deze kolom is ook leeg. 
- userflag: voor alle waarden 0, wordt dit voor iets specifiek gebruikt?
- calc_speed_2d: is dit de berekende snelheid in 2D? Wat is dan het verschil met de kolom 'speed_2d' + is deze waarde betrouwbaar?

Daarnaast zeiden jullie dat de gemeten hoogte niet betrouwbaar is. Alle kolommen die dus iets met hoogte te maken hebben zoals altitude_agl, h_accuracy en speed 3D kloppen dus waarschijnlijk niet?

@JanBaert

**Comment by peterdesmet** [comment]
* `is_active`: is a legacy column that was added to the metadata but wasn't used. **ignore**
* `pressure`: is a column in the source database for GPS trackers that measure air pressure. Our trackers to do not. **ignore**
* `userflag`: is a column in the source database where researchers can set records they consider invalid. Have never seen this used. **ignore**
* `calc_speed_2d`: is a column added by our data processing pipeline, indicating the trajectory speed between point `n` and point `n-1`. `speed_2d` is a column in the source database, which is the instantaneous speed measured by the tag. Those speeds are thus different concepts. We use `calc_speed_2d` to notice outliers: e.g. if that speed is > 30m/s (108km/h), then the GPS point is probably an outlier on the track that should not be used.

And indeed, the `altitude` measured by the GPS tag has quite an error range. I am not sure however if this affects `speed_3d`.

Note: this file might be useful to get more insights in useful columns: https://github.com/inbo/bird-tracking/blob/master/sql/movebank_gps.sql. It maps columns in our data (UvA-BiTS format) with internationally used columns used in Movebank (which have their definitions at https://www.movebank.org/node/2381#data) with UvA-BiTS columns (= our data).
