### ISSUE TITLE
Status of the progress and results?

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/geo-ict-student-project-2018#5]
@ThibeautFormesyn @MaartenBlomme @joliedegeyter any progress on the data analysis so far? Any questions or issues that @JanBaert or myself can address?

**Comment by ThibeautFormesyn** [comment]
@stijnvanhoey we are currently testing some different data analysis approaches. At this moment, I don't believe they are specific questions. When we have finished some things, we will show them to you.
